name: code
description: "A Flutter project demonstrating the usage of Flutter Hooks and Hook Widget patterns"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
